services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    env_file:
      - ./mysql/.env
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
networks:
  transform:

volumes:
  mysql_data:  